language: python
python:
  - 2.6
  - 2.7
env:
  - NSQ_DOWNLOAD=nsq-0.3.0.linux-amd64.go1.3.3 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.3.0.linux-amd64.go1.3.3 TORNADO_VERSION=4.1
  - NSQ_DOWNLOAD=nsq-0.3.1.linux-amd64.go1.4.1 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.3.1.linux-amd64.go1.4.1 TORNADO_VERSION=4.1
  - NSQ_DOWNLOAD=nsq-0.3.2.linux-amd64.go1.4.1 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.3.2.linux-amd64.go1.4.1 TORNADO_VERSION=4.1
  - NSQ_DOWNLOAD=nsq-0.3.5.linux-amd64.go1.4.2 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.3.5.linux-amd64.go1.4.2 TORNADO_VERSION=4.1
  - NSQ_DOWNLOAD=nsq-0.3.6.linux-amd64.go1.5.1 TORNADO_VERSION=3.2
  - NSQ_DOWNLOAD=nsq-0.3.6.linux-amd64.go1.5.1 TORNADO_VERSION=4.1
script: 
  - ./travis_test.sh
notifications:
  email: false
sudo: false
